project:
  type: website
  output-dir: docs

website:
  title: HTA hub
  page-footer: Developed during the 2024 HTA hackathon at Queens University Belfast, UK
  navbar:
    logo: images/logo.png
    left:
      - icon: github
        href: https://htahackathon2024.github.io/HERA
      - href: index.qmd
        text: Home
      - href: getstarted.qmd
        text: Get Started
      - href: hub.qmd
        text: Visit the Hub

reader-mode: false
format:
  html:
    theme: 
      light: [litera]
      dark: [superhero]
    toc: true
    toc-location: left
