project:
  type: website
  output-dir: docs

website:
  title: HERA - Health Economics in R for All
  page-footer: Developed during the 2024 HTA hackathon at Queen's University Belfast, UK
  navbar:
    logo: logo.jpg
    left:
      - icon: github
        href: https://htahackathon2024.github.io/HERA
      - href: index.qmd
        text: Home
      - href: getstarted.qmd
        text: Get Started

reader-mode: false
format:
  html:
    theme: 
      light: [litera]
      dark: [superhero]
    toc: true
    toc-location: left
