on:
  push:
    branches:
      - i13
      - main

name: Render and Publish

permissions:
     contents: write
     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Render and publish to GH pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
